# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ecZ-_FGGhPcSQMDpxPgHN6zFfA3QxkyU
"""

import numpy as np
import pandas as pd
import math

mylist  = list("abcdefghijklmnopqrstuvwxyz")
myarr = np.arange(26)
mydict = dict(zip(mylist,myarr))
ser = pd.DataFrame({"numeros": myarr , "letras": mylist})

ser.head()

ser1 = pd.Series([1,2,3,4,5])
ser2 = pd.Series([4,5,6,7,8])

result = ser1.isin(ser2)

ser1[~result]

df = pd.DataFrame({"col1":ser1, "col2":ser2})
df.head()

ser4 = np.random.randint(1,10,35)
ser2=np.resize(ser4,(7,5))
ser2 = pd.DataFrame(ser2)
ser2

arr1 = "test"
aux2 = pd.Series(["how","to","kick","ass?"])
aux2 = aux2.apply(lambda x : x[0].upper() + x[1:])
aux2

p = pd.Series([1,2,3,4,5,6,7,8,9,10])
q = pd.Series([10,9,8,7,6,5,4,3,2,1])
r = q-p
r